
my_app : "실전투자 app 키"
my_sec : "실전투자 appsecret 키"

paper_app : "모의투자 app 키"
paper_sec : "모의투자 appsecret 키"

my_paper_stock : "모의투자 계좌번호"
my_acct_stock : "실전투자 계좌번호"

vps : "https://openapivts.koreainvestment.com:29443"  # 모의투자 url
prod : "https://openapi.koreainvestment.com:9443"     # 실전투자 url

